import SlickSlider from '@/components/slickSlider/SlickSlider';
import Head from 'next/head'

const images = [
  'https://robertelliotthomes.com/wp-content/uploads/2020/11/Luxury-homes-in-Dallas.jpg',
  'https://cdn.onekindesign.com/wp-content/uploads/2019/03/Contemporary-Home-Design-Stocker-Hoesterey-Montenegro-Architects-01-1-Kindesign.jpg',
  'https://www.rocketmortgage.com/resources-cmsassets/RocketMortgage.com/Article_Images/Large_Images/TypesOfHomes/types-of-homes-hero.jpg',
];

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Header /> */}
        <SlickSlider images={images} />
      {/* <Footer /> */}
    </>
  )
}